### ISSUE TITLE
Preserve ordering

### ISSUE THREAD

**Issue by delijati** [Pylons/peppercorn#11]
The `dict` should be replaced with `collections.OrderedDict`.

**Comment by mcdonc** [comment]
Tres kindly implemented a PR for this issue in https://github.com/Pylons/peppercorn/pull/15 .  I'm not totally against merging it, but I'd like to understand the rationale behind asking for it before we do.

**Comment by delijati** [comment]
It's some time ago since i created this issue. I think the comment https://github.com/Pylons/peppercorn/pull/15#issuecomment-413747190 explains the use case.

**Comment by delijati** [comment]
Hmm it is really long ago and it was probably for some customer. I think it was for generating reports or sending emails or something like this. The ordering in the form should be preserved in the `appstruct`.

**Comment by mcdonc** [comment]
OK, thanks.  I am hesitantly going to reject the patch from @tseaver because there doesn't appear to be a heart-must-continue-beating reason to accept it; if someone else comes up with a defensible case for it, we can reopen.
